config/routes.rb
Tach::Application.routes.draw do
  resources :apps

  get "index" => "home#index"

  root :to => 'home#index'

end

app/models/app.rb
class App < ActiveRecord::Base
  attr_accessible :desc, :level, :name, :statu
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  # GET /apps
  # GET /apps.json
  def index
    @apps = App.all
    @apps_grid = initialize_grid(App)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @apps }
    end
  end

  # GET /apps/1
  # GET /apps/1.json
  def show
    @app = App.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @app }
    end
  end

  # GET /apps/new
  # GET /apps/new.json
  def new
    @app = App.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @app }
    end
  end

  # GET /apps/1/edit
  def edit
    @app = App.find(params[:id])
  end

  # POST /apps
  # POST /apps.json
  def create
    @app = App.new(params[:app])

    respond_to do |format|
      if @app.save
        format.html { redirect_to @app, notice: 'App was successfully created.' }
        format.json { render json: @app, status: :created, location: @app }
      else
        format.html { render action: "new" }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /apps/1
  # PUT /apps/1.json
  def update
    @app = App.find(params[:id])

    respond_to do |format|
      if @app.update_attributes(params[:app])
        format.html { redirect_to @app, notice: 'App was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apps/1
  # DELETE /apps/1.json
  def destroy
    @app = App.find(params[:id])
    @app.destroy

    respond_to do |format|
      format.html { redirect_to apps_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/apps/_form.html.slim
= form_for @app do |f|
  - if @app.errors.any?
    #error_explanation
      h2 = "#{pluralize(@app.errors.count, "error")} prohibited this app from being saved:"
      ul
        - @app.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :statu
    = f.text_field :statu
  .field
    = f.label :level
    = f.text_field :level
  .field
    = f.label :desc
    = f.text_area :desc
  .actions = f.submit 'Save'

app/views/apps/_grid.html.erb
<%= grid(@apps_grid) do |g|

  g.column :name => "ID", :attribute => "id", :filter => false do |app|
    app.id
  end

  g.column :name => "Name", :attribute => "name" do |app|
    app.name
  end

  g.column :name => "Statu", :attribute => "statu" do |app|
    app.statu
  end

  g.column :name => "Level", :attribute => "level" do |app|
    app.level
  end

  g.column :name => "Desc", :attribute => "desc" do |app|
    app.desc
  end


  g.column do |app|
    link_to('Edit', edit_app_path(app))
  end
end -%>

app/views/apps/edit.html.slim
h1 Editing app

== render 'form'

= link_to 'Show', @app
'|
= link_to 'Back', apps_path

app/views/apps/index.html.slim
h1 Listing apps

= render 'apps/grid'

/ table
/   tr
/     th Name
/     th Statu
/     th Level
/     th Desc
/     th
/     th
/     th

/   - @apps.each do |app|
/     tr
/       td = app.name
/       td = app.statu
/       td = app.level
/       td = app.desc
/       td = link_to 'Show', app
/       td = link_to 'Edit', edit_app_path(app)
/       td = link_to 'Destroy', app, :confirm => 'Are you sure?', :method => :delete

/ br

= link_to 'New App', new_app_path

app/views/apps/new.html.slim
h1 New app

== render 'form'

= link_to 'Back', apps_path

app/views/apps/show.html.slim
p#notice = notice

p
  strong Name:
  = @app.name
p
  strong Statu:
  = @app.statu
p
  strong Level:
  = @app.level
p
  strong Desc:
  = @app.desc

= link_to 'Edit', edit_app_path(@app)
'|
= link_to 'Back', apps_path

app/views/home/index.html.slim
br

app/views/layouts/_dashboard.slim
section#dashboard
  h1 Hello! What would you like to do?
  /! Breadcumbs
  ul#breadcrumbs
    li
      a href="/" title="Back to Homepage" Home
    li
      a href="#" Projects
    li
      a href="#" Projects's Assets
    li
      a href="#" Edit Assets
    li Current Page
  /! /Breadcumbs
  /! Nav Shortcuts
  ul.shortcuts
    li.shortcut-contacts
      a href="" title=""
    li.shortcut-sales
      a href="" title=""
    li.shortcut-tickets
      a href="apps" title="apps'
      span.small-notification 3
    li.shortcut-articles
      a href="" title=""
    li.shortcut-looong
      a href="" title=""
    li.shortcut-settings
      a href="" title=""
      span.small-notification 47
  /! /Nav Shortcuts

app/views/layouts/_footer.slim
footer#footer
  .page-wrapper
    section
      h2 Vestibulum blandit massa
      p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dignissim auctor dolor. Curabitur a arcu nec massa malesuada eleifend vel sit amet magna. Nulla vel leo sit amet justo porttitor vulputate ut vel sapien. Sed quis enim augue, id elementum quam.
      p Ut vel aliquet leo. Suspendisse quis fringilla ligula. Suspendisse potenti. Nam volutpat pellentesque est, sed mattis ante interdum et.
      /! Social Sub Nav List Style
      ul.social-list
        li
          a.social.rss href="#"
        li
          a.social.twitter href="#"
        li
          a.social.facebook href="#"
        li
          a.social.forrst href="#"
        li
          a.social.tumblr href="#"
      /! /Social Sub Nav List Style
    section
      h2 Praesent facilisis
      ul
        li
          a href="#"
        li
          a href="#"
        li
          a href="#"
        li
          a href="#"
        li
          a href="#"
        li
          a href="#"
        li
          a href="#"
        li
          a href="#"
    section
      h2 Cras tellus nisi
      form.vertical-form
        dl
          dt
            label Short Input
          dd
            input name="" type="text" value=""
          dt
            label Textarea
          dd
            textarea.footer cols="40" name="" rows="5"
        button.gray type="submit"

app/views/layouts/_header.slim
header#navigation
  /! Navigation Container
  .navigation-wrapper
    /! Your Project Logo
    a#logo href="/" title="Back to Homepage"
    /! Main Nav Container
    nav#nav-main
      /! Main Navigation
      ul#nav-main-navigation
        li
          a href="index" title="首页" 首页
        li
          a.nav-main-subnav href="#submenu-1" title="应用" 应用
        li
          a.nav-main-subnav href="#submenu-2" title=""
          span.small-notification style="display: block; "
        li
          a.nav-main-subnav href="#submenu-3" title=""
        li
          a.nav-main-subnav href="#submenu-4" title=""
      /! /Main Navigation
      /! User Navigation
      ul#nav-main-user
        li
          | Welcome,
          a href="#" title=""
        li
          a.actions href="#" title="Messages"
            img alt="Messages" src="/assets/img/icons/icon_user_message.png"
        li
          a.actions href="#" title="Settings"
            img alt="Settings" src="/assets/img/icons/icon_user_settings.png"
        li
          a.actions href="#" title="Logout"
            img alt="Logout" src="/assets/img/icons/icon_user_logout.png"
      /! /User Navigation
    /! /Main Nav Container
    /! Sub Nav Container
    nav#nav-sub style="height: 0px; "
      /! Sub Nav Block #submenu-1
      #submenu-1.submenu style="display: none; "
        /! Standard Sub Nav List Style
        /! Use class .menu-fit to indent list under 1st main menu item
        ul.standard-list.menu-fit
          li.standard-list-header
            h2 Some Links
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
        /! /Standard Sub Nav List Style
        ul.standard-list
          li.standard-list-header
            h2 Useful Links
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
        ul.standard-list
          li.standard-list-header
            h2 More Links
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
        /! If you don't want headers in lists use class .header-fit to indent list verticaly to fit lists with headers
        ul.standard-list.header-fit
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
        ul.standard-list.header-fit
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a.outside href="http://www.parallaq.com"
      /! /Sub Nav Block #submenu-1
      /! Sub Nav Block #submenu-2
      #submenu-2.submenu style="display: none; "
        ul.standard-list.menu-fit
          li.standard-list-header
            h2 Some Links
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
        /! Box Sub Nav List Style
        ul.box-list
          li.box-list-header
            h2 Useful Links
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
        /! /Box Sub Nav List Style
        ul.box-list.header-fit
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
        ul.box-list.header-fit
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
          li
            a href="#"
        /! You can also use articles in submenu, they will automatically align to the right or use class .perex to align left
        article
          h2 Header H2
          p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse et dignissim metus. Maecenas id augue ac metus tempus aliquam.
      /! /Sub Nav Block #submenu-2
      /! Sub Nav Block #submenu-3
      #submenu-3.submenu style="display: none; "
        /! Thumbnail Sub Nav List Style
        ul.thumbnail-list.menu-fit
          li.thumbnail-list-header
            h2 Image Content
          li
            img alt="Sample Image" src="/assets/img/_sample-data/sample_image_1.png"
              h3 Some image examples
              p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse et dignissim metus.
              a.thumbnail-list-more Read more »
          li
            img alt="Sample Image" src="/assets/img/_sample-data/sample_image_2.png"
              h3 One more example
              p Sed pharetra placerat est suscipit sagittis. Phasellus aliquam malesuada blandit.
              a.thumbnail-list-more Read more »
        /! /Thumbnail Sub Nav List Style
        /! You can also use articles in submenu, they will automatically align to the right or use class .perex to align left
        article
          h2 Header H2
          p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse et dignissim metus. Maecenas id augue ac metus tempus aliquam.
      /! /Sub Nav Block #submenu-3
      /! Sub Nav Block #submenu-4
      #submenu-4.submenu style="display: none; "
        /! Sub Nav Form
        form.submenu-form.menu-fit
          fieldset
            legend Lorem ipsum dolor
            dl
              dt.clear-tm
                label Login
              dd
                input name="" type="text" value=""
              dt
                label Password
              dd
                input name="" type="password" value=""
            button.gray type="submit"
        /! /Sub Nav Form
        article
          h2 Header H2
          p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse et dignissim metus. Maecenas id augue ac metus tempus aliquam.
          h3 Header H3
          p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse et dignissim metus. Maecenas id augue ac metus tempus aliquam.
        /! Social Sub Nav List Style
        ul.social-list
          li
            a.social.rss href="#"
          li
            a.social.twitter href="#"
          li
            a.social.facebook href="#"
          li
            a.social.forrst href="#"
          li
            a.social.tumblr href="#"
        /! /Social Sub Nav List Style
      /! /Sub Nav Block #submenu-4

app/views/layouts/_modal.slim
#sample.modal-content
  h1 nyroModal
  p Ajax Call, Ajax Call with targeting content, Single Image, Images Gallery with arrow navigating, Gallery with any kind of content, Form, Form in iframe, Form with targeting content, Form with file upload, Form with file upload with targeting content, Dom Element, Manual Call, Iframe, Stacked Modals, Many embed element through Embed.ly API, Error handling, Modal will never goes outside the view port, Esc key to close the window, Customizable animation, Customizable look, Modal title.
  a.outside href="http://nyromodal.nyrodev.com/"

app/views/layouts/application.html.slim
doctype
html
  head
    title Tach
    = stylesheet_link_tag    "application", :media => "all"
    = csrf_meta_tags
  body
    = render 'layouts/header'
    section.page-wrapper role="main" style="min-height:580px;"
      = render 'layouts/dashboard'
      = yield
    
    = render 'layouts/footer'
    /.loading-notification Loading…
    = render 'layouts/modal'
    a#toTop href="#" style="display: inline; "
	  span#toTopHover style="opacity: 0; " To Top

  = javascript_include_tag "jquery-1.5.1.min", "application"